image: gcc
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - apt-get update
  - apt-get install -y python-pip cmake
  - pip install gcovr

build:
  script:
    - cd src
    - mkdir build
    - cmake -S . -B build -DTEST_COVERAGE=On
    - cmake --build build -j

test:
  script:
    - make test -C build

coverage:
  script:
    - make coverage -C build
