image: gcc

stages:
  - build
  - test
  - coverage

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - src/build

before_script:
  - apt-get update
  - apt-get install -y python-pip cmake
  - pip install gcovr

build:
  stage: build
  script:
    - mkdir src/build -p
    - cmake -S src -B src/build -DTEST_COVERAGE=On
    - cmake --build src/build -j
  artifacts:
    paths:
      - src/build

test:unittests:
  stage: test
  script:
    - make test -C src/build
  artifacts:
    paths:
      - src/build

test:coverage:
  stage: coverage
  script:
    - make coverage -C src/build
  dependencies:
    - test:unittests
