image: romeov/fasterslam_docker

stages:
  - build
  - test
  - coverage

info:
  stage: build
  script: g++ -E -march=native -dM - < /dev/null | grep -i avx

build:
  stage: build
  script:
    - mkdir src/build -p
    - cmake -S src -B src/build -DTEST_COVERAGE=On
    - cmake --build src/build -j 2
  artifacts:
    paths:
      - src/build

unittests:
  stage: test
  script:
    - make test -C src/build
  artifacts:
    paths:
      - src/build

valgrind:
  stage: test
  script:
    - cd src/build
    - ctest . -T memcheck --overwrite MemoryCheckCommandOptions="--leak-check=full --error-exitcode=1"

benchmarks:
  stage: test
  script:
    - mkdir src/build_release -p
    - cmake -S src -B src/build_release -DCMAKE_BUILD_TYPE=Release
    - make -C src/build_release benchmarks

coverage:
  stage: coverage
  script:
    - make coverage -C src/build
  dependencies:
    - unittests
