image: gcc
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - apt-get update
  - apt-get install python-pip -y
  - pip install gcovr

build_test:
  script:
    - cd src
    - mkdir build
    - cmake -S . -B build -DTEST_COVERAGE=On
    - cmake --build build -j

test:
  script:
    - make test -C build

coverage:
  script:
    - make coverage -C build
