image: romeov/fasterslam_docker

stages:
  - build
  - test
  - coverage

cache:
  paths:
    - src/build

build:
  stage: build
  script:
    - mkdir src/build -p
    - cmake -S src -B src/build -DTEST_COVERAGE=On
    - cmake --build src/build -j
  artifacts:
    paths:
      - src/build

test:unittests:
  stage: test
  script:
    - make test -C src/build
  artifacts:
    paths:
      - src/build

test:unittests:
  stage: test
  script:
    - make test -C src/build
  artifacts:
    paths:
      - src/build

test:valgrind:
  stage: test
  script:
    - cd src/build
    - ctest . -T memcheck

test:coverage:
  stage: coverage
  script:
    - make coverage -C src/build
  dependencies:
    - test:unittests
